version: "3.8"

services:
  # Backend API
  backend:
    build: .
    container_name: campus-navigation-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      # Use Atlas MongoDB URI instead of local container
      MONGODB_URI: mongodb+srv://ua5122843:6339usmanUSMAN804@cluster0.1z1zr.mongodb.net/visit?retryWrites=true&w=majority&appName=Cluster0
      JWT_SECRET: your_super_secret_jwt_key_change_in_production
      JWT_EXPIRE: 7d
      FRONTEND_URL: http://localhost:5173
      MAX_FILE_SIZE: 10485760
      UPLOAD_PATH: ./uploads
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - campus-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: campus-navigation-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./uploads:/var/www/uploads:ro
    depends_on:
      - backend
    networks:
      - campus-network

networks:
  campus-network:
    driver: bridge
